### ISSUE TITLE
batch method seems not defined

### ISSUE THREAD

**Issue by djiworks** [mcollina/levelgraph#131]
Hi,
First of all, your library was very useful.

Actually, I used it with sublevel and I found something strange.
It seems that batch method is not defined:
Example:
```
var levelup = require("level");
var sublevel = require("level-sublevel");
var levelgraph = require("levelgraph");

var db = levelup("yourdb");
console.log(db.batch); // Prints function

db = sublevel(db);
console.log(db.batch); // Prints function

var graph = levelgraph(db.sublevel('graph'));
console.log(graph.batch); // Prints undefined

var triple = { subject: "a", predicate: "b", object: "c" };
var putBatch = graph.generateBatch(triple);
graph.batch(putBatch, function() {
  console.log(arguments);
});
```
Doing this I got:
graph.batch(putBatch, function() {
      ^
TypeError: Object #<Object> has no method 'batch'
    at Object.<anonymous> (..../index.js:19:7)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by mcollina** [comment]
You need to use the batch method of the underlining sublevel/level instance.
Il giorno dom 30 ago 2015 alle 15:04 Djothi Grondin <
notifications@github.com> ha scritto:

**Comment by djiworks** [comment]
Well. One of my ideas was:
```
// fast hack
levelgraph2 = function (levelDb, options) {
  db = levelgraph(levelDb, options);
  db.batch = levelDb.batch.bind(levelDb)
  return db
};

graph = levelgraph2(db.sublevel('graph2'));
```
Thanks for your time.
